# Generated by Django 6.0.3 on 2026-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserve_target_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='roles',
        ),
        migrations.AlterField(
            model_name='role',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.position'),
        ),
    ]
