# Generated by Django 6.0.3 on 2026-04-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_position_roles_alter_role_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR-специалист'), ('manager', 'Руководитель'), ('director', 'Директор'), ('employee', 'Сотрудник')], default='employee', max_length=30),
        ),
    ]
