# Generated by Django 4.2.7 on 2026-03-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(verbose_name='Требуемый уровень')),
                ('weight', models.FloatField(default=1.0, verbose_name='Весовой коэффициент')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.competency', verbose_name='Компетенция')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Идеальный профиль',
                'verbose_name_plural': 'Идеальные профили',
                'unique_together': {('position', 'competency')},
            },
        ),
    ]
