# Generated by Django 4.2.7 on 2026-03-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_date', models.DateField(auto_now_add=True, verbose_name='Дата включения')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=2, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('target_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Целевая должность')),
            ],
            options={
                'verbose_name': 'Кадровый резерв',
                'verbose_name_plural': 'Кадровый резерв',
                'ordering': ['-priority'],
            },
        ),
    ]
