# Generated by Django 6.0.3 on 2026-04-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evaluation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.competency'),
        ),
        migrations.AddField(
            model_name='position',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='positions', to='core.competency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'HR-специалист'), ('manager', 'Руководитель'), ('employee', 'Сотрудник')], default='employee', max_length=30),
        ),
        migrations.CreateModel(
            name='PositionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveIntegerField(default=60, verbose_name='Требуемый уровень (0-100)')),
                ('weight', models.FloatField(default=0.15, verbose_name='Вес')),
                ('is_key', models.BooleanField(default=False, verbose_name='Ключевая компетенция')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competency', verbose_name='Компетенция')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Профиль должности',
                'verbose_name_plural': 'Профили должностей',
                'ordering': ['position', '-is_key', 'weight'],
                'unique_together': {('position', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('default_missing_level', models.PositiveIntegerField(default=20, verbose_name='Уровень по умолчанию при отсутствии оценки (0-100)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.department')),
                ('positions', models.ManyToManyField(blank=True, related_name='role_set', to='core.position')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='position_set', to='core.role'),
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveIntegerField(default=60, verbose_name='Требуемый уровень (0-100)')),
                ('weight', models.FloatField(default=0.15, verbose_name='Вес (сумма по роли ≈ 1.0)')),
                ('is_key', models.BooleanField(default=False, verbose_name='Обязательная компетенция')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competency')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.role')),
            ],
            options={
                'verbose_name': 'Профиль роли',
                'verbose_name_plural': 'Профили ролей',
                'unique_together': {('role', 'competency')},
            },
        ),
        migrations.DeleteModel(
            name='IdealProfile',
        ),
    ]
