# Generated by Django 6.0.3 on 2026-04-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_competencies_position_competencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
    ]
