# Generated by Django 6.0.3 on 2026-04-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='default_missing_level',
        ),
    ]
