# Generated by Django 6.0.3 on 2026-04-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_role_default_missing_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
