# Generated by Django 6.0.3 on 2026-04-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_options_user_email_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='competencies',
        ),
        migrations.RemoveField(
            model_name='position',
            name='competencies',
        ),
    ]
